baseURL = "/"
languageCode = "ja"
title = "tamrin.me"
theme = "kiss"
copyright = "&copy; <a href=\"https://github.com/tamrin007\">Tamrin007</a> 2018"
Paginate = 5
enableRobotsTXT = true

[params.info]
enableSocial = true
homeTitle = "tamrin.me"
poweredby = false
related = true

[params.opengraph.twitter]
page = "tamrin007"

[params.social]
twitter = "tamrin007"
github = "tamrin007"

[permalinks]
post = "/:year/:month/:day/:filename"

[taxonomies]
tag ="tags"

[blackfriday]
hrefTargetBlank = true

